### ISSUE TITLE
Is it possible to have a docker version?

### ISSUE THREAD

**Issue by tonyzhou777** [edirpedro/vnstat-dashboard#1]
Hello. A docker version would be very convenient for different environments. Is it possible to have one?

Thanks.

**Comment by edirpedro** [comment]
I don't use Docker, but you can up any web server image and host it. I tried Nginx here, follow the steps:

1. Download the repository and move the folder `/build` to where you want to save the app, rename it if you want.
2. In this folder create a file `docker-compose.yml` and write on it:

```
version: "3.9"
name: vnstat_dashboard

services:
  web:
    image: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/usr/share/nginx/html
```

3. Open the Terminal and on this folder type `docker-compose up -d`
4. Follow the steps to make the **Crontab** send the reports to `/location/to/build/api` every 5 minutes.
5. Open `http://localhost:8000`. Make sure the report file are available on the api folder.

Tell me if this works, maybe a I can put this option available. 
I wanted to use a custom domain like "vnstat.local" but I couldn't find an easy step to setup this on Docker.
